# Generated by Django 4.2.21 on 2025-05-29 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_allowedemail_level'),
        ('accounts', '0002_alter_faculty_id_alter_user_first_name_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='allowed_email',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.allowedemail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.department'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer'), ('Teaching Assistant', 'Teaching Assistant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
