# Generated by Django 4.2.21 on 2025-05-28 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_faculty_id_alter_user_first_name_alter_user_id'),
        ('courses', '0002_alter_assessmentcomponent_id_alter_assessmentmark_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-year', 'semester', 'section_number']},
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_template_public',
        ),
        migrations.RemoveField(
            model_name='section',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='section',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='section',
            name='faculties',
            field=models.ManyToManyField(related_name='sections', to='accounts.faculty'),
        ),
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course'),
        ),
    ]
