# Generated by Django 4.2.21 on 2025-05-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='total_classes',
            field=models.PositiveIntegerField(default=28, help_text='Total number of classes for attendance calculation'),
        ),
    ]
