# Generated by Django 4.2.21 on 2025-05-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_section_total_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
