# Generated by Django 4.2.21 on 2025-05-29 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_faculty_allowed_email_alter_faculty_department_and_more'),
        ('courses', '0003_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-year', 'semester', 'name']},
        ),
        migrations.RenameField(
            model_name='section',
            old_name='section_number',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='section',
            name='primary_faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primary_sections', to='accounts.faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='secondary_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_sections', to='accounts.faculty'),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'name', 'year', 'semester')},
        ),
        migrations.RemoveField(
            model_name='section',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='section',
            name='updated_at',
        ),
    ]
