# Generated by Django 4.2.21 on 2025-05-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('Regular', 'Regular Student'), ('Transfer', 'Transfer Student')], default='Regular', max_length=50),
        ),
    ]
