# Generated by Django 4.2.21 on 2025-06-01 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_session_is_holiday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmenttemplate',
            old_name='is_public',
            new_name='is_published',
        ),
        migrations.AddField(
            model_name='assessmentmark',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assessmentmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_marks', to='courses.student'),
        ),
        migrations.AlterField(
            model_name='assessmenttemplate',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_template', to='courses.section'),
        ),
        migrations.CreateModel(
            name='AssessmentItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_count', models.IntegerField(choices=[(1, 'Top 1'), (2, 'Top 2')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.clo')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_groups', to='courses.assessmenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assessment_type', models.CharField(choices=[('Assessment', 'Assessment'), ('Midterm', 'Midterm'), ('Final', 'Final')], max_length=20)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.clo')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_items', to='courses.assessmentitemgroup')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_items', to='courses.assessmenttemplate')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='assessmentmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assessmentmark',
            name='assessment_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='courses.assessmentitem'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='assessmentmark',
            unique_together={('assessment_item', 'student')},
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.student')),
            ],
            options={
                'ordering': ['session__session_number'],
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.RemoveField(
            model_name='assessmentmark',
            name='component',
        ),
        migrations.RemoveField(
            model_name='assessmentmark',
            name='mark',
        ),
        migrations.DeleteModel(
            name='AssessmentComponent',
        ),
    ]
