# Generated by Django 4.2.21 on 2025-05-29 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollment_enrollment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_sl', models.IntegerField()),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_groups', to='courses.section')),
            ],
            options={
                'ordering': ['section', 'group_sl'],
                'unique_together': {('section', 'group_sl')},
            },
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Backlog', 'Backlog'), ('Self-Study', 'Self-Study')], default='Regular', max_length=50),
        ),
        migrations.CreateModel(
            name='ProjectGroupEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.projectgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.student')),
            ],
            options={
                'unique_together': {('project_group', 'student')},
            },
        ),
    ]
