# Generated by Django 4.2.21 on 2025-07-08 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_assessmentitem_id_alter_assessmentitemgroup_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentitemgroup',
            name='item1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_item1', to='courses.assessmentitem'),
        ),
        migrations.AddField(
            model_name='assessmentitemgroup',
            name='item10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_item10', to='courses.assessmentitem'),
        ),
        migrations.AddField(
            model_name='assessmentitemgroup',
            name='item2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_item2', to='courses.assessmentitem'),
        ),
        migrations.AddField(
            model_name='assessmentitemgroup',
            name='item3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_item3', to='courses.assessmentitem'),
        ),
        migrations.AddField(
            model_name='assessmentitemgroup',
            name='item4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_item4', to='courses.assessmentitem'),
        ),
        migrations.AddField(
            model_name='assessmentitemgroup',
            name='item5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_item5', to='courses.assessmentitem'),
        ),
        migrations.AddField(
            model_name='assessmentitemgroup',
            name='item6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_item6', to='courses.assessmentitem'),
        ),
        migrations.AddField(
            model_name='assessmentitemgroup',
            name='item7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_item7', to='courses.assessmentitem'),
        ),
        migrations.AddField(
            model_name='assessmentitemgroup',
            name='item8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_item8', to='courses.assessmentitem'),
        ),
        migrations.AddField(
            model_name='assessmentitemgroup',
            name='item9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_item9', to='courses.assessmentitem'),
        ),
        migrations.AddField(
            model_name='assessmentitemgroup',
            name='totalmarks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessmentitemgroup',
            name='max_count',
            field=models.IntegerField(choices=[(1, 'Top 1'), (2, 'Top 2'), (3, 'Top 3'), (4, 'Top 4'), (5, 'Top 5'), (6, 'Top 6'), (7, 'Top 7'), (8, 'Top 8'), (9, 'Top 9'), (10, 'Top 10')], default=1),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall')], max_length=10),
        ),
    ]
