# Generated by Django 4.2.21 on 2025-07-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_assessmentitemgroup_item1_assessmentitemgroup_item10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentitem',
            name='in_group',
            field=models.BooleanField(default=False),
        ),
    ]
