# Generated by Django 4.2.21 on 2025-05-26 20:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('CE', 'Civil Engineering'), ('EEE', 'Electrical and Electronic Engineering')], max_length=10)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
