# Generated by Django 4.2.21 on 2025-05-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_allowedemail_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedemail',
            name='level',
            field=models.IntegerField(choices=[(1, '1. Highest Access Faculty'), (2, '2. High Access Faculty '), (3, '3. Mid Access Faculty'), (4, '4. General Faculty')], default=4),
        ),
    ]
