# Generated by Django 4.2.21 on 2025-05-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_plo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('CE', 'Civil Engineering'), ('EEE', 'Electrical and Electronic Engineering')], max_length=10)),
                ('level', models.IntegerField(choices=[(1, '1. Highest Access'), (2, '2. High Access '), (3, '3. Mid Access'), (4, '4. Faculty')], default=4)),
            ],
        ),
    ]
