# Generated by Django 4.2.21 on 2025-05-26 20:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_program_department_name_alter_program_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedemail',
            name='department_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='allowedemail',
            name='description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allowedemail',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.department'),
        ),
    ]
