# Generated by Django 4.2.21 on 2025-05-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_allowedemail_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedemail',
            name='description',
        ),
    ]
