# Generated by Django 4.2.21 on 2025-05-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_remove_allowedemail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedemail',
            name='department_name',
            field=models.CharField(blank=True, default='will be auto set', max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='department_name',
            field=models.CharField(blank=True, default='will be auto set', max_length=100),
        ),
    ]
