# Generated by Django 4.2.21 on 2025-05-26 20:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_alter_allowedemail_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
